<a href="https://colab.research.google.com/github/RodrigoARivasG/datawarehouse-seguros/blob/main/Notebooks/etl_aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/RodrigoARivasG/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [ ]:
df = pd.read_csv(url)
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

Limpieza de datos

In [8]:
#Estructura del archivo
print("Dimensiones:", df.shape)
print("\nColumnas:")
print(df.columns)
print("\nTipos de datos:")
print(df.dtypes)

Dimensiones: (15, 4)

Columnas:
Index(['id_aseguradora', 'nombre', 'pais', 'rating_riesgo'], dtype='object')

Tipos de datos:
id_aseguradora     int64
nombre            object
pais              object
rating_riesgo     object
dtype: object

In [9]:
#valores nulos
print(df.isnull().sum())

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [10]:
aseguradoras = df.copy()

In [11]:
aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()
aseguradoras.columns

Index(['id_aseguradora', 'nombre', 'pais', 'rating_riesgo'], dtype='object')

In [12]:
for col in aseguradoras.select_dtypes(include="object").columns:
    aseguradoras[col] = aseguradoras[col].str.strip()

In [13]:
aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

In [14]:
print("Duplicados antes:", aseguradoras.duplicated().sum())

aseguradoras = aseguradoras.drop_duplicates()

print("Duplicados después:", aseguradoras.duplicated().sum())

Duplicados antes: 0
Duplicados después: 0

In [15]:
aseguradoras["pais"] = aseguradoras["pais"].replace({
    "ElSalvador": "El Salvador",
    "elsalvador": "El Salvador",
    "ELSALVADOR": "El Salvador"
})

In [16]:
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].replace({
    "A": "Alto",
    "B": "Bajo",
    "C": "Medio",
    "D": "Desconocido"
})

In [17]:
validos = aseguradoras[
    aseguradoras["id_aseguradora"].notna() &
    aseguradoras["nombre"].notna() &
    aseguradoras["pais"].notna() &
    aseguradoras["rating_riesgo"].notna()
].copy()

In [18]:
rechazados = aseguradoras[
    aseguradoras["pais"].isna() |
    aseguradoras["rating_riesgo"].isna()
].copy()

In [19]:
def motivo_rechazo(row):
    motivos = []

    if pd.isna(row["pais"]):
        motivos.append("pais_vacio")

    if pd.isna(row["rating_riesgo"]):
        motivos.append("rating_riesgo_vacio")

    return ", ".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo, axis=1)

In [20]:
print("Cantidad de válidos:", len(validos))
print("Cantidad de rechazados:", len(rechazados))

Cantidad de válidos: 10
Cantidad de rechazados: 5

In [21]:
validos

    id_aseguradora          nombre         pais rating_riesgo
0                1   Aseguradora 1   Costa Rica          Alto
1                2   Aseguradora 2  El Salvador          Bajo
3                4   Aseguradora 4   Costa Rica         Medio
4                5   Aseguradora 5  El Salvador          Bajo
6                7   Aseguradora 7    Guatemala          Alto
7                8   Aseguradora 8       Panamá          Bajo
10              11  Aseguradora 11     Honduras   Desconocido
11              12  Aseguradora 12  El Salvador          Bajo
12              13  Aseguradora 13     Honduras          Alto
14              15  Aseguradora 15  El Salvador          Alto

In [22]:
rechazados

,id_aseguradora,nombre,pais,rating_riesgo,motivo_rechazo
2,3,Aseguradora 3,El Salvador,NaN,rating_riesgo_vacio
5,6,Aseguradora 6,NaN,Medio,pais_vacio
8,9,Aseguradora 9,NaN,Bajo,pais_vacio
9,10,Aseguradora 10,Panamá,NaN,rating_riesgo_vacio
13,14,Aseguradora 14,El Salvador,NaN,rating_riesgo_vacio

In [23]:
validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [25]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_rivas:ks9EQNpC43n64cYY21G6e2BUn85omaRa@dpg-d6qu610gjchc73en58b0-a.oregon-postgres.render.com/etl_seguros_h814"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 33.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [29]:
validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

5

In [30]:
pd.read_sql(
"SELECT * FROM aseguradoras_curated LIMIT 10",
engine
)

   id_aseguradora          nombre         pais rating_riesgo
0               1   Aseguradora 1   Costa Rica          Alto
1               2   Aseguradora 2  El Salvador          Bajo
2               4   Aseguradora 4   Costa Rica         Medio
3               5   Aseguradora 5  El Salvador          Bajo
4               7   Aseguradora 7    Guatemala          Alto
5               8   Aseguradora 8       Panamá          Bajo
6              11  Aseguradora 11     Honduras   Desconocido
7              12  Aseguradora 12  El Salvador          Bajo
8              13  Aseguradora 13     Honduras          Alto
9              15  Aseguradora 15  El Salvador          Alto